Example PR
iO-Academy/git-workshop pull request #48
Opened 2020-10-13 13:18 UTC by mporam

2020-10-13 13:26 UTC, Sass77 requested changes

2020-10-13 13:26 UTC, Sass77 commented on index.html
> +for sarah to see
comment here

2020-10-13 13:26 UTC, Sass77 commented on index.html
> +this is a BAD line of code >:|
another comment

2020-10-13 13:28 UTC, Sass77 approved these changes

2021-07-09 15:59 UTC, norayna approved these changes

2022-03-11 15:22 UTC, closed without merging